<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>pl.fistach</groupId>
    <artifactId>java-cli-application-architecture-archetype</artifactId>
    <packaging>pom</packaging>
    <version>1.1.0</version>

    <name>Maven Archetype for Java CLI application with clean architecture</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.deploy.skip>true</maven.deploy.skip>
    </properties>

    <scm>
        <connection>scm:git:https://github.com/fistach/java-cli-application-clean-architecture-archetype.git</connection>
        <developerConnection>scm:git:git@github.com:fistach/java-cli-application-clean-architecture-archetype.git</developerConnection>
        <tag>java-cli-application-architecture-archetype-1.1.0</tag>
    </scm>

    <distributionManagement>
        <repository>
            <id>central</id>
            <url>https://central.sonatype.com/api/v1/publisher</url>
        </repository>
    </distributionManagement>

    <modules>
        <module>java-cli-clean-architecture-archetype</module>
        <module>java-clean-architecture-archetype-with-spring</module>
        <module>archetype-test</module>
    </modules>
</project>
