archetypeGroupId=io.github.fistach.archetypes
archetypeArtifactId=java-clean-architecture-archetype-with-spring
archetypeVersion=1.0.0-SNAPSHOT
groupId=com.example
artifactId=calculator
version=1.0-SNAPSHOT
package=com.example.main
interactiveMode=false
archetypeCatalog=internal
