archetypeGroupId=pl.fistach
archetypeArtifactId=java-cli-clean-architecture-archetype
archetypeVersion=1.0-SNAPSHOT
groupId=com.example
artifactId=calculator
version=1.0-SNAPSHOT
interactiveMode=false
archetypeCatalog=internal
