archetypeGroupId=io.github.fistach.archetypes
archetypeArtifactId=java-cli-clean-architecture-archetype
archetypeVersion=1.0-SNAPSHOT
groupId=com.example
artifactId=calculator
version=1.0-SNAPSHOT
package=com.example.main
interactiveMode=false
archetypeCatalog=internal
